version: 2
services:
  - type: web
    name: csgo-discord-bot
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run prisma:deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
